In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
flights = pd.read_csv("../data/flights.csv")
airlines = pd.read_csv("../data/airlines.csv")
airports = pd.read_csv("../data/airports.csv")

/var/folders/ff/cx5j06tx19bd86gp38lmblr40000gn/T/ipykernel_59443/1626780985.py:1: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  flights = pd.read_csv("../data/flights.csv")

In [3]:
flights.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
flights.shape

(5819079, 31)

In [5]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 31 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 int64
 1   MONTH                int64
 2   DAY                  int64
 3   DAY_OF_WEEK          int64
 4   AIRLINE              object
 5   FLIGHT_NUMBER        int64
 6   TAIL_NUMBER          object
 7   ORIGIN_AIRPORT       object
 8   DESTINATION_AIRPORT  object
 9   SCHEDULED_DEPARTURE  int64
 10  DEPARTURE_TIME       float64
 11  DEPARTURE_DELAY      float64
 12  TAXI_OUT             float64
 13  WHEELS_OFF           float64
 14  SCHEDULED_TIME       float64
 15  ELAPSED_TIME         float64
 16  AIR_TIME             float64
 17  DISTANCE             int64
 18  WHEELS_ON            float64
 19  TAXI_IN              float64
 20  SCHEDULED_ARRIVAL    int64
 21  ARRIVAL_TIME         float64
 22  ARRIVAL_DELAY        float64
 23  DIVERTED             int64
 24  CANCELLED            int64
 25  CANCELLATION_REASON  object
 26  AIR_SYSTEM_DELAY     float64
 27  SECURITY_DELAY       float64
 28  AIRLINE_DELAY        float64
 29  LATE_AIRCRAFT_DELAY  float64
 30  WEATHER_DELAY        float64
dtypes: float64(16), int64(10), object(5)
memory usage: 1.3+ GB

In [6]:
airlines.head()

  IATA_CODE                 AIRLINE
0        UA   United Air Lines Inc.
1        AA  American Airlines Inc.
2        US         US Airways Inc.
3        F9  Frontier Airlines Inc.
4        B6         JetBlue Airways

In [7]:
airports.head()

,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,ABE,Lehigh Valley International Airport,Allentown,PA,USA,40.65236,-75.44040
1,ABI,Abilene Regional Airport,Abilene,TX,USA,32.41132,-99.68190
2,ABQ,Albuquerque International Sunport,Albuquerque,NM,USA,35.04022,-106.60919
3,ABR,Aberdeen Regional Airport,Aberdeen,SD,USA,45.44906,-98.42183
4,ABY,Southwest Georgia Regional Airport,Albany,GA,USA,31.53552,-84.19447

In [8]:
flights.columns

Index(['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'FLIGHT_NUMBER',
       'TAIL_NUMBER', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT',
       'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY', 'TAXI_OUT',
       'WHEELS_OFF', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
       'WHEELS_ON', 'TAXI_IN', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME',
       'ARRIVAL_DELAY', 'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON',
       'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY',
       'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY'],
      dtype='object')

In [9]:
df = flights[
    [
        "YEAR",
        "MONTH",
        "DAY",
        "DAY_OF_WEEK",

        "AIRLINE",
        "FLIGHT_NUMBER",

        "ORIGIN_AIRPORT",
        "DESTINATION_AIRPORT",

        "SCHEDULED_DEPARTURE",
        "DEPARTURE_TIME",
        "DEPARTURE_DELAY",

        "SCHEDULED_ARRIVAL",
        "ARRIVAL_TIME",
        "ARRIVAL_DELAY",

        "DISTANCE",
        "CANCELLED",
        "CANCELLATION_REASON"
    ]
]

In [10]:
df.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DISTANCE,CANCELLED,CANCELLATION_REASON
0,2015,1,1,4,AS,98,ANC,SEA,5,2354.0,-11.0,430,408.0,-22.0,1448,0,NaN
1,2015,1,1,4,AA,2336,LAX,PBI,10,2.0,-8.0,750,741.0,-9.0,2330,0,NaN
2,2015,1,1,4,US,840,SFO,CLT,20,18.0,-2.0,806,811.0,5.0,2296,0,NaN
3,2015,1,1,4,AA,258,LAX,MIA,20,15.0,-5.0,805,756.0,-9.0,2342,0,NaN
4,2015,1,1,4,AS,135,SEA,ANC,25,24.0,-1.0,320,259.0,-21.0,1448,0,NaN

In [11]:
df.shape

(5819079, 17)

In [12]:
df.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           86153
DEPARTURE_DELAY          86153
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             92513
ARRIVAL_DELAY           105071
DISTANCE                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
dtype: int64

In [13]:
df["CANCELLED"].value_counts()

CANCELLED
0    5729195
1      89884
Name: count, dtype: int64

In [14]:
df = df[df["CANCELLED"] == 0]

In [15]:
df = df.drop(
    columns=["CANCELLATION_REASON"]
)

In [16]:
df.reset_index(
    drop=True,
    inplace=True
)

In [17]:
df.shape

(5729195, 16)

In [18]:
df.isnull().sum()

YEAR                       0
MONTH                      0
DAY                        0
DAY_OF_WEEK                0
AIRLINE                    0
FLIGHT_NUMBER              0
ORIGIN_AIRPORT             0
DESTINATION_AIRPORT        0
SCHEDULED_DEPARTURE        0
DEPARTURE_TIME             0
DEPARTURE_DELAY            0
SCHEDULED_ARRIVAL          0
ARRIVAL_TIME            2629
ARRIVAL_DELAY          15187
DISTANCE                   0
CANCELLED                  0
dtype: int64

In [19]:
df = df.dropna()

df.reset_index(
    drop=True,
    inplace=True
)

In [20]:
df.isnull().sum()

YEAR                   0
MONTH                  0
DAY                    0
DAY_OF_WEEK            0
AIRLINE                0
FLIGHT_NUMBER          0
ORIGIN_AIRPORT         0
DESTINATION_AIRPORT    0
SCHEDULED_DEPARTURE    0
DEPARTURE_TIME         0
DEPARTURE_DELAY        0
SCHEDULED_ARRIVAL      0
ARRIVAL_TIME           0
ARRIVAL_DELAY          0
DISTANCE               0
CANCELLED              0
dtype: int64

In [21]:
df.shape

(5714008, 16)

In [22]:
df = df.merge(
    airlines,
    left_on="AIRLINE",
    right_on="IATA_CODE",
    how="left"
)

df.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE_x,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DISTANCE,CANCELLED,IATA_CODE,AIRLINE_y
0,2015,1,1,4,AS,98,ANC,SEA,5,2354.0,-11.0,430,408.0,-22.0,1448,0,AS,Alaska Airlines Inc.
1,2015,1,1,4,AA,2336,LAX,PBI,10,2.0,-8.0,750,741.0,-9.0,2330,0,AA,American Airlines Inc.
2,2015,1,1,4,US,840,SFO,CLT,20,18.0,-2.0,806,811.0,5.0,2296,0,US,US Airways Inc.
3,2015,1,1,4,AA,258,LAX,MIA,20,15.0,-5.0,805,756.0,-9.0,2342,0,AA,American Airlines Inc.
4,2015,1,1,4,AS,135,SEA,ANC,25,24.0,-1.0,320,259.0,-21.0,1448,0,AS,Alaska Airlines Inc.

In [23]:
df.drop(
    columns=[
        "AIRLINE_x",
        "IATA_CODE"
    ],
    inplace=True
)

In [24]:
df.rename(
    columns={
        "AIRLINE_y":"AIRLINE"
    },
    inplace=True
)

In [25]:
df.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DISTANCE,CANCELLED,AIRLINE
0,2015,1,1,4,98,ANC,SEA,5,2354.0,-11.0,430,408.0,-22.0,1448,0,Alaska Airlines Inc.
1,2015,1,1,4,2336,LAX,PBI,10,2.0,-8.0,750,741.0,-9.0,2330,0,American Airlines Inc.
2,2015,1,1,4,840,SFO,CLT,20,18.0,-2.0,806,811.0,5.0,2296,0,US Airways Inc.
3,2015,1,1,4,258,LAX,MIA,20,15.0,-5.0,805,756.0,-9.0,2342,0,American Airlines Inc.
4,2015,1,1,4,135,SEA,ANC,25,24.0,-1.0,320,259.0,-21.0,1448,0,Alaska Airlines Inc.

In [26]:
df["DATE"] = pd.to_datetime(
    df[["YEAR", "MONTH", "DAY"]]
)

In [27]:
df[
    [
        "YEAR",
        "MONTH",
        "DAY",
        "DATE"
    ]
].head()

   YEAR  MONTH  DAY       DATE
0  2015      1    1 2015-01-01
1  2015      1    1 2015-01-01
2  2015      1    1 2015-01-01
3  2015      1    1 2015-01-01
4  2015      1    1 2015-01-01

In [28]:
df["MONTH_NAME"] = df["DATE"].dt.month_name()

In [29]:
df[
    [
        "DATE",
        "MONTH",
        "MONTH_NAME"
    ]
].head()

        DATE  MONTH MONTH_NAME
0 2015-01-01      1    January
1 2015-01-01      1    January
2 2015-01-01      1    January
3 2015-01-01      1    January
4 2015-01-01      1    January

In [30]:
df["IS_DELAYED"] = np.where(
    df["ARRIVAL_DELAY"] > 15,
    1,
    0
)

In [31]:
df["IS_DELAYED"].value_counts()

IS_DELAYED
0    4690510
1    1023498
Name: count, dtype: int64

In [32]:
delay_percentage = (
    df["IS_DELAYED"].mean() * 100
)

delay_percentage

np.float64(17.91208552735663)

In [33]:
def delay_status(delay):

    if delay <= 0:
        return "Early / On Time"

    elif delay <= 15:
        return "Slight Delay"

    elif delay <= 60:
        return "Moderate Delay"

    else:
        return "Major Delay"


df["DELAY_STATUS"] = (
    df["ARRIVAL_DELAY"]
    .apply(delay_status)
)

In [34]:
df["DELAY_STATUS"].value_counts()

DELAY_STATUS
Early / On Time    3627112
Slight Delay       1063398
Moderate Delay      704406
Major Delay         319092
Name: count, dtype: int64

In [35]:
def time_period(time):

    hour = int(time // 100)

    if 5 <= hour < 12:
        return "Morning"

    elif 12 <= hour < 17:
        return "Afternoon"

    elif 17 <= hour < 21:
        return "Evening"

    else:
        return "Night"


df["TIME_PERIOD"] = (
    df["SCHEDULED_DEPARTURE"]
    .apply(time_period)
)

In [36]:
df["TIME_PERIOD"].value_counts()

TIME_PERIOD
Morning      2341610
Afternoon    1720139
Evening      1287578
Night         364681
Name: count, dtype: int64

In [37]:
df.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,...,ARRIVAL_TIME,ARRIVAL_DELAY,DISTANCE,CANCELLED,AIRLINE,DATE,MONTH_NAME,IS_DELAYED,DELAY_STATUS,TIME_PERIOD
0,2015,1,1,4,98,ANC,SEA,5,2354.0,-11.0,...,408.0,-22.0,1448,0,Alaska Airlines Inc.,2015-01-01,January,0,Early / On Time,Night
1,2015,1,1,4,2336,LAX,PBI,10,2.0,-8.0,...,741.0,-9.0,2330,0,American Airlines Inc.,2015-01-01,January,0,Early / On Time,Night
2,2015,1,1,4,840,SFO,CLT,20,18.0,-2.0,...,811.0,5.0,2296,0,US Airways Inc.,2015-01-01,January,0,Slight Delay,Night
3,2015,1,1,4,258,LAX,MIA,20,15.0,-5.0,...,756.0,-9.0,2342,0,American Airlines Inc.,2015-01-01,January,0,Early / On Time,Night
4,2015,1,1,4,135,SEA,ANC,25,24.0,-1.0,...,259.0,-21.0,1448,0,Alaska Airlines Inc.,2015-01-01,January,0,Early / On Time,Night

In [38]:
df.shape

(5714008, 21)

In [39]:
df.columns

Index(['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'FLIGHT_NUMBER',
       'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT', 'SCHEDULED_DEPARTURE',
       'DEPARTURE_TIME', 'DEPARTURE_DELAY', 'SCHEDULED_ARRIVAL',
       'ARRIVAL_TIME', 'ARRIVAL_DELAY', 'DISTANCE', 'CANCELLED', 'AIRLINE',
       'DATE', 'MONTH_NAME', 'IS_DELAYED', 'DELAY_STATUS', 'TIME_PERIOD'],
      dtype='object')

In [40]:
df.to_csv(
    "../data/processed/cleaned_flights.csv",
    index=False
)

In [42]:
cleaned = pd.read_csv(
    "../data/processed/cleaned_flights.csv"
)

cleaned.head()

/var/folders/ff/cx5j06tx19bd86gp38lmblr40000gn/T/ipykernel_59443/3130077963.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  cleaned = pd.read_csv(

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,...,ARRIVAL_TIME,ARRIVAL_DELAY,DISTANCE,CANCELLED,AIRLINE,DATE,MONTH_NAME,IS_DELAYED,DELAY_STATUS,TIME_PERIOD
0,2015,1,1,4,98,ANC,SEA,5,2354.0,-11.0,...,408.0,-22.0,1448,0,Alaska Airlines Inc.,2015-01-01,January,0,Early / On Time,Night
1,2015,1,1,4,2336,LAX,PBI,10,2.0,-8.0,...,741.0,-9.0,2330,0,American Airlines Inc.,2015-01-01,January,0,Early / On Time,Night
2,2015,1,1,4,840,SFO,CLT,20,18.0,-2.0,...,811.0,5.0,2296,0,US Airways Inc.,2015-01-01,January,0,Slight Delay,Night
3,2015,1,1,4,258,LAX,MIA,20,15.0,-5.0,...,756.0,-9.0,2342,0,American Airlines Inc.,2015-01-01,January,0,Early / On Time,Night
4,2015,1,1,4,135,SEA,ANC,25,24.0,-1.0,...,259.0,-21.0,1448,0,Alaska Airlines Inc.,2015-01-01,January,0,Early / On Time,Night

In [43]:
cleaned.shape

(5714008, 21)